### PR TITLE
Update license to CC BY-SA

### PR DESCRIPTION
**Pull request by skaven81**

### CODE REVIEW

**Comment by skaven81** [comment]
@i-grow-carrots should comment on this before merging

**Comment by xalioth** [comment]
That was fast :)
+1

**Comment by skaven81** [comment]
I'm sure the `.po` files were generated by some translation utility or something, so it may not be right for me to go in and manually update them.  I'm also making an assumption that when the `msgstr` is an empty string, that this means "just use the original string and don't rewrite it".  If that's not the case then I can update it so that the `msgstr` matches the `msgid` (as it was for some of the translation files).

**Comment by xalioth** [comment]
Yes, the update_po.py script use google translate to translate missing translation in selected languages.
But manually editing is fine also, just keep it this way

**Comment by skaven81** [comment]
I think @i-grow-carrots is not going to respond -- he's not responded to the e-mail thread.  I think this is OK to merge.

**Pull request merged**
