### PR TITLE
Update en.po to fix grammar

### PR DESCRIPTION
**Pull request by jidanni**
P.S., there are in fact several files with the same error. I'll just fix this one.

### CODE REVIEW

**Comment by 10110111** [comment]
This entry (`msgid`) should match the source that's located in `description.md`.

**Comment by jidanni** [comment]
I better stop now. I would probably only mess it up more.

**Comment by xalioth** [comment]
Hi jidani,

thanks for your help. I will close this PR, because the fix needs to be done in the file chinese/description.md
All the .po files will be automatically updated in a second step by running the update_po.py script.

**Comment by jidanni** [comment]
Please do make sure the PO files have warnings on the top of each one, in the comments inside them, to avoid people accidentally editing them by mistake.

**Pull request closed without merging**
